---
abstract: 'objects as resistant to dying as John Maclane'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Die::Hard
name: Die-Hard
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Moo: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Die-Hard
  homepage: https://metacpan.org/release/Die-Hard
  license: http://dev.perl.org/licenses/
version: 0.002
